name: XPBottle
api: 3.0.0
main: Frozt\XPBottle
version: 1.0
commands:
  xpbottle:
    description: Redeem XP into XP Bottles.
  exp:
    description: Check your current experience.
  addxp:
    description: Add XP to yourself or others.
  removexp:
    description: Romove XP from yourself or others.
   
permission:
  redeem.exp:
    default: true
  xp.addown:
    default: false
  xp.addothers:
    default: false
  xp.removeown:
    default: false
  xp.removeothers:
    default: false
